### ISSUE TITLE
Long run time on very large RNAseq data

### ISSUE THREAD

**Issue by chrisamiller** [pmelsted/pizzly#27]
Hey Pall, 

I've got a very large RNAseq data set from one sample that contains about ~6 billion reads (paired, ~3B in each of R1/R2).  Kallisto completes just fine on it, but the fusions output file contains 48 million entries, and is 21GB in size.  (compare this to a "standard" RNAseq run on the same sample that has ~150M reads, with only 268k lines in the fusion output file) 

When I run pizzly on this large dataset, it's churning away at 100% CPU, but after nearly 24h is still running.  Any tips for speeding up the process?

Alternately, if I know the transcripts that I expect to be fused (based on the smaller RNAseq data set), is there a straightforward way to extract the supporting reads from the fusions output file?  I could just grep for lines containing the known transcript pairings, but I worry that I'll be missing out on the additional filtering described in the pizzly paper.  Thanks!

**Comment by pmelsted** [comment]
Hi Chris

Even "very large" is an understatement. I haven't implemented multithreading because most datasets are much smaller than that, but that's on my list.

If you want to grep/awk for lines, you can do it on the fusion.txt file directly and then run pizzly on the grepped output. A simple `grep -f txlist.txt` should do it, pizzly will then read this file and apply all the appropriate filters.

Hope this helps

**Comment by chrisamiller** [comment]
Thanks - grepping out my transcripts of interest, then running pizzly on that seems to have gotten me what I need!
