### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [pmelsted/pizzly#3]
I have a server where I can not upgrade  my system (I use RHEL 5.5) I have some issue on library. If I try to use  pre compiled  version I have this error:

/pizzly: symbol lookup error: ./pizzly: undefined symbol: _ZNSt7__cxx117collateIcE2idE

Could you please help me?
thanks so much

**Comment by pmelsted** [comment]
The binary works with centos 6 (rhel 6) or later. Because we use c++14, which requires a recent gcc this was the best I could do.

If you have access to another machine you can move the fusion.txt files there and run them there.

I will look into making this work for older systems, but I don't know if it will work properly.

**Comment by bioinfo-dirty-jobs** [comment]
thanks so much!

**Comment by pmelsted** [comment]
I've put some effort into this and it seems that gcc 5 and later is not compatible with rhel 5 since the glibc is too old. This makes it pretty much impossible to distribute binaries for older systems, so we will be focusing on centos/rhel 6 or later.
